"""Add Uplift model

Revision ID: 71c4bff121c2
Revises: 79cefec5be09
Create Date: 2019-10-01 12:22:37.417515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71c4bff121c2'
down_revision = '79cefec5be09'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uplifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('repository', sa.String(length=30), nullable=True),
    sa.Column('user_impact', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('risky', sa.Text(), nullable=True),
    sa.Column('bug_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('string_changes', sa.Text(), nullable=True),
    sa.Column('automated_tests', sa.Boolean(), nullable=True),
    sa.Column('nightly', sa.Boolean(), nullable=False),
    sa.Column('risk', sa.Enum('low', 'medium', 'high', name='upliftrisk'), nullable=False),
    sa.Column('requester_email', sa.String(length=254), nullable=True),
    sa.Column('status', sa.Enum('created', 'approved', 'rejected', 'landed', 'failed', name='upliftstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'repository', name='uplift_revision_repository')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uplifts')
    # ### end Alembic commands ###
